services:
  db:
    image: postgres:16-alpine
    container_name: bookstore_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  worker:
    build: .
    container_name: bookstore_worker
    command: npm run dev:worker
    env_file: .env
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
    networks:
      - app_net

  redis:
    image: redis:7-alpine
    container_name: bookstore_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    networks:
      - app_net

volumes:
  db_data:
  redis_data:

networks: 
  app_net:
    driver: bridge
